### ISSUE TITLE
checkScoverage doesn't work with aggregateScoverage

### ISSUE THREAD

**Issue by TomaszDudziak** [scoverage/gradle-scoverage#44]
`gradle clean reportScoverage aggregateScoverage checkScoverage`
results in
`java.io.FileNotFoundException: <my_project>\build\reports\scoverage\cobertura.xml (The system cannot find the path specified)`
That file is actually here
`<my_project>\build\scoverage-aggregate\cobertura.xml`

**Comment by maiflai** [comment]
Hi,

Does your root project have source code? 

I've been using this task with a root project on windows 7 and OS X which does not have source code.

You also need to add a dependency such that aggregateScoverage depends on all reportScoverage tasks.

Thanks,
Sri

**Comment by TomaszDudziak** [comment]
No, the root project doesn't contain source code. 
What do you mean by making `aggregateScoverage` depend on `reportScoverage`?

To be clear, I do not have any problems with `aggregateScoverage`. This works fine:
`gradle clean reportScoverage aggregateScoverage`
This works fine too:
`gradle clean reportScoverage checkScoverage`

I get an exception only when running:
`gradle clean reportScoverage aggregateScoverage checkScoverage`

This exception is not because of my project's structure, but because aggregateScoverage creates a folder **scoverage-aggregate** rather than the expected **scoverage** in the build folder of the root project. That is why file `<my_project>\build\reports\scoverage\cobertura.xml` cannot be found (see the exception above).

**Comment by maiflai** [comment]
re: dependencies - `aggregateScoverage` creates a new aggregated set of reports in the **scoverage-aggregate** folder.

In order for it to do this, all of the sub-project `reportScoverage` tasks must have been previously completed. In my projects I create a single aggregated report of all sub-projects, so I tend to add this dependency in a single `subprojects` block.

re: `checkScoverage` - this task reads the project-specific **cobertura.xml** rather than the aggregated version. If you have an empty root project then you probably need to disable its checkScoverage task because the scoverage report directory will be empty. I think this is an 'feature' because it was originally intended to fail the build when no coverage at all is recorded - I'll have a further think.

as a workaround, in the root project, please could you try:

```groovy
checkScoverage.enabled = false
```

or to actually check the aggregated scoverage file I think the following should work:

```groovy
checkScoverage {
  dependsOn aggregateScoverage
  cobertura = file("$buildDir/scoverage-aggregate/cobertura.xml")
}
```

Thanks,
Stu

**Comment by TomaszDudziak** [comment]
Adding the cobertura property pointing to the right file fixed the problem. Thanks for help, Stu.

**Comment by maiflai** [comment]
No worries, hope you find the results useful.
