### ISSUE TITLE
Why does gradle-scoverage create testScoverage task?

### ISSUE THREAD

**Issue by denisrosca** [scoverage/gradle-scoverage#57]
This is a more of a question instead of an issue, but I can't apply labels...
As the title says I'm wondering why does gradle-scoverage define a separate `testScoverage` task to execute the tests?
I'm running a build that has both scoverage and sonarqube plugins applied. The issue is that in this case the tests are executed twice (sonar has a dependency on the test task) which messes up the build times.

A different implementation would be similar to the cobertura plugin, which adds instrumentation & reporting tasks, but uses the default `test` task defined in the build.

**Comment by maiflai** [comment]
At the time I wanted to use tasks rather than build properties to control such a core part of the build; Gradle doesn't do a great job of determining task staleness when build properties change.

It's also less invasive to enrich the build with extra tasks; I had to work around the Jacoco plugin when building the ScalaTest plugin.

Can you configure Sonar to use the test results from testScoverage and skip the test task?

**Comment by maiflai** [comment]
I should add - I think it's possible to build a scoverage plugin that modifies the existing tasks, but it has its own complexity. I might take another look over the weekend if I get a chance.

**Comment by mayur9991** [comment]
@maiflai did you figure out to merge testCoverage task with test task ? as this has a big impact on build time if you have 1000+ tests.

**Comment by maiflai** [comment]
Hi,

`testScoverage` and `test` work over entirely different inputs; scoverage creates instrumented output that cannot be deployed.

If you only want to run one set of tests, and get scoverage results, then I suggest disabling the test task? This can be done dynamically so that if both are selected, only one is run.

Stu

**Comment by mayur9991** [comment]
Disabling test task is not an option as I have complex project with Java, Scala, Python and other front-end code. Probably I will run scala test on different node to generate coverage. Thanks!

**Comment by eyalroth** [comment]
@maiflai 

I imagine it should be possible to get both scoverage and another tool -- say cobertura -- to work together and generate reports on the same test execution. 

That is, assuming that each tool is responsible for instrumenting and reporting coverage for different classes; for instance, cobertura for Java classes and scoverage for Scala classes. After all, if both tools will instrument the same class, only one implementation will be loaded by the class-loader, and thus only one report will be generated for the class during the test execution.

Both scoverage and cobertura output their instrumented classes to directories (one is in `build/classes/scala/scoverage`, the other is in `build/instrumented_classes`), so isn't it only a matter of adding both of these directories to the classpath of the test execution?

**Comment by eyalroth** [comment]
It was hell, but I made it work on my [mixed Java-Scala multi-module gradle example project](https://github.com/eyalroth/java-scala-gradle-project):
```
gradle test - only runs tests and normal compilation

gradle aggregateScoverage - runs the tests after both normal compilation and compilation with scoverage, and generates an aggregated report for scala classes only

gradle cobertura - runs the tests after both normal compilation and cobertura instrumentation, and generates an aggregated cobertura report for java classes only

gradle testCoverage - runs the tests only once after normal compilation, compilation with scoverage and cobertura instrumentation, and generates aggregated reports for both scoverage (scala classes only) and cobertura (java classes only) 
```

The real hell was due to both scoverage and cobertura outputting all of the classes, even those excluded from instrumentation. I had to made sure to delete all the java classes from the scoverage output directory, and all the scala classes from the cobertura output directory. This way, there are no class collisions when it comes to the classpath.

It would make life easier if the gradle scoverage plugin will make sure to delete all the excluded classes after the compilation with scoverage is finished (same goes for cobertura and other coverage tools).

**Comment by alisiikh** [comment]
Hi,

I managed to instrument the existing tasks instead of using the testScoverage, plus I did the same thing to integrationTest sourcset and task but not including them for simplicity:

```gradle
apply plugin: 'org.scoverage'

sourceSets {
    test {
        scala {
            compileClasspath += scoverage.output
            runtimeClasspath += scoverage.output + configurations.scoverage
        }
    }
}

test {
    classpath = sourceSets.test.output + 
            sourceSets.scoverage.output + 
            configurations.scoverage + 
            sourceSets.test.runtimeClasspath
}

// remove the taskScoverage task dependency added by scoverage plugin
// we will just reuse the test task
reportScoverage.dependsOn.remove(testScoverage)
reportScoverage.dependsOn(test)

```

Hope it helps somebody who needs something similar.

**Comment by eyalroth** [comment]
@alisiikh There are two problems with this solution:

1. `test` now depends on `compileScoverageScala`, making the build much much longer (what if you want to run the tests without coverage?). The correct way of doing this is removing the `sourceSets` section, and adding the dependency `test.mustRunAfter(compileScoverageScala)`.

2. It still might not work with other coverage tools; for instance, it will definitely not work with cobertura. See my previous comment for more details on that.

**Comment by eyalroth** [comment]
I've updated my example project with a slightly different approach for deleting the non-instrumented files of both scoverage and cobertura.

The previous method relied on the names of the java soruce files, which turned out to not support inner classes correctly. The new method simply compares the instrumented files with the normally compiled files, deleting files from the instrumentation directory if they are identical to their normally compiled counterpart (meaning they are not instrumented at all). 

This new method might not work correctly with lambdas in certain versions of Java 8, as it seems there is [a bug making classes with lambda to be compiled nondeterministically](https://bugs.openjdk.java.net/browse/JDK-8067422); though, cobertura [doesn't seem to support lambdas](https://github.com/cobertura/cobertura/issues/166) anyhow.

**Comment by eyalroth** [comment]
@maiflai I believe this issue could be closed now that there's no more `testScoverage` task (as of version 3.0.0).
