### ISSUE TITLE
mark Inputs and Outputs of tasks

### ISSUE THREAD

**Issue by ssp** [scoverage/gradle-scoverage#69]
Since we started using gradle’s build cache to speed up our build, I noticed that the coverage reported by the »reportScoverage« task sometimes drops to 0. This is unfortunate.

In these situations, gradle considers the »testScoverage« task as »UP-TO-DATE« even though the build/scoverage/scoverage.measurements.* files it generates do not exist.

My guess is that this issue is caused by gradle-scoverage’s tasks not marking their inputs and outputs and gradle wrongly assuming there is nothing to do as a consequence.

**Comment by maiflai** [comment]
Sorry for the delay.

That's a little odd, unless you have deliberately set `clean = true` on your aggregating report task.

I seem to recall that the data directory is wiped by the compiler plugin on compilation, which should automatically invalidate any test task (because the compiled classes will also change). 

Perhaps it's a quirk of some incremental compilation options that you have set?

Please could you try adding the following to your build to see if it helps. If so I'll see about making it the default behaviour.

```groovy
testScoverage.outputs.dir(scoverage.dataDir)
```

Thanks,
Stu.

**Comment by ssp** [comment]
Hi @maiflai,

sorry for taking so long to get back to you – I must have overlooked the notification for your comment.

My impression is that the correct handling of caching in the 2.3.0 release resolves this issue. Thanks for that!

Sven
