### ISSUE TITLE
How to use coverageDebug

### ISSUE THREAD

**Issue by rpau** [scoverage/gradle-scoverage#72]
Hi, 

I am interested to see the tests output from scoverage. I think that it can be fixed with the coverageDebug flag. However, I can not find any example to use it. Could you point me out how to set this flag?

**Comment by maiflai** [comment]
I think the following should work:
```groovy
scoverage.coverageDebug = true
```
Please could you let me know how you get on?

Thanks,
Stu

**Comment by rpau** [comment]
It produced the same output. I would love to see every test that it is executed and if it has failed, but I can not.

**Comment by maiflai** [comment]
I think this sounds like a general gradle question, rather than anything specific to the scoverage plugin.

In recent gradle releases test tasks are silent unless they fail; at which point you will see the failed test and assertion printed to the console.

If you don't trust it then you can add `--info` to the command line which should show the tests being run (in addition to information from other tasks).

Have you configured the default `test` task to print the required information?

Stu.

**Comment by maiflai** [comment]
Please can this issue be closed?

Thanks,
Stu
