### ISSUE TITLE
scoverage doesn't work properly when scalatest is a separate task

### ISSUE THREAD

**Issue by scr-oath** [scoverage/gradle-scoverage#77]
If you use the property: `com.github.maiflai.gradle-scalatest.mode = append` to enable running scalatest and java test framework (testNG, e.g.) then scoverage doesn't report anything.

**Comment by scr-oath** [comment]
See https://github.com/maiflai/gradle-scalatest/pull/47#issuecomment-334959925

**Comment by maiflai** [comment]
Sorry, on review I can't spot where a problem would appear (from the gradle-scoverage perspective).

As you say, running gradle-scalatest in append mode means that the `testScoverage` task should be run using the default Gradle test runner i.e. JUnit. 

Are you saying that you want gradle-scalatest to run testScoverage because all your Scala modules are using ScalaTest?

If so, I think you might try this within a Scala module:

```
com.github.maiflai.ScalaTestPlugin.configure(
  tasks.test, 
  new com.github.maiflai.BackwardsCompatibleJavaExecActionFactory(gradle.gradleVersion)
)
```


Can you provide a project that I can take a look at?

Thanks,
Stu.

**Comment by scr-oath** [comment]
Hi - I haven't looked at this in a while either… I'll close this for now, and if I can reproduce when trying to get both test frameworks working again, I'll send you a reduced gist as example.

**Comment by Coobik** [comment]
hi all!
is there a solution of running coverage on both legacy tests (gradle test) AND scalatest tests (gradle scalatest)?
thanks!
